# Generated by Django 4.2.11 on 2024-04-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0003_userprofile_role_alter_userprofile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
