# Generated by Django 4.2.11 on 2024-04-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_element_text', models.TextField(blank=True, null=True)),
                ('first_element_image', models.ImageField(blank=True, null=True, upload_to='pair_images/')),
                ('second_element_text', models.TextField(blank=True, null=True)),
                ('second_element_image', models.ImageField(blank=True, null=True, upload_to='pair_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='findpairtask',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='findpairtask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='findpairtask',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PairElement',
        ),
        migrations.AddField(
            model_name='pair',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='study_buddy.findpairtask'),
        ),
    ]
