# Generated by Django 4.2.11 on 2024-04-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0008_pair_remove_findpairtask_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='task',
        ),
        migrations.DeleteModel(
            name='FindPairTask',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
