# Generated by Django 4.2.11 on 2024-05-01 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0013_alter_pair_first_element_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='first_element_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='pair',
            name='second_element_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
