# Generated by Django 4.2.11 on 2024-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0014_pair_first_element_id_pair_second_element_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='first_element_id',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='second_element_id',
        ),
        migrations.AddField(
            model_name='pair',
            name='pair_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
