# Generated by Django 4.2.11 on 2024-05-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0015_remove_pair_first_element_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='pair_number',
        ),
    ]
