# Generated by Django 4.2.11 on 2024-05-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0017_studentresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResponse',
        ),
    ]
