# Generated by Django 4.2.11 on 2024-05-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0019_completedtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='grade',
            new_name='score',
        ),
    ]
