# Generated by Django 4.2.11 on 2024-05-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_buddy', '0020_rename_grade_completedtask_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='score',
            new_name='grade',
        ),
    ]
